version: "3.8"

services:
  web:
    image: php:8.2-apache
    container_name: gamestore_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      sed -ri -e 's!/var/www/html!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
      && sed -ri -e 's!/var/www/!$${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
      && a2enmod rewrite
      && docker-php-ext-install pdo pdo_mysql
      && apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: gamestore_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamestore_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: gamestore_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
